# Generated by Django 4.1.3 on 2022-11-13 12:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('sche_date', models.DateTimeField(default=datetime.datetime.now)),
                ('place', models.CharField(blank=True, max_length=50, null=True)),
                ('repeatition', models.CharField(blank=True, max_length=5, null=True)),
                ('notification', models.DateTimeField(blank=True, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
